approvedGitRepositories:
  - "https://github.com/electron/node-gyp.git"

checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

logFilters:
  - code: YN0086
    level: discard
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard
  - code: YN0013
    level: discard

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 1w

yarnPath: .yarn/releases/yarn-4.16.0.cjs
