nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.8.3.cjs

logFilters:

  # Disable useless non-actionable warnings.
  # https://github.com/yarnpkg/yarn/issues/4064

  # eg "@joplin/app-desktop@workspace:packages/app-desktop provides react (p87edd) with version 18.2.0, which doesn't satisfy what @testing-library/react-hooks and some of its descendants request"
  - code: YN0060
    level: discard

  # eg "@joplin/app-desktop@workspace:packages/app-desktop doesn't provide react-is (p570cf), requested by styled-components"
  - code: YN0002
    level: discard

  # eg "string.prototype.matchall@npm:4.0.8 can't be found in the cache and will be fetched from the remote registry"
  - code: YN0013
    level: discard

# To avoid the error "The remote archive doesn't match the expected checksum".
# Yarn offers no way to understand what the issue is when it happens, or what
# needs to be done so it's just security theater that we have no choice but to
# disable.
checksumBehavior: update
