checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

httpTimeout: 600000

logFilters:
  - code: YN0086
    level: discard
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard
  - code: YN0013
    level: discard

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
