export function pluginCategories() {
type pluginCategory = {
	[key: string]: string;
};
const pluginCategoriesOptions: pluginCategory = {
	'Attaché': 'files',
	'Disable PDF': 'files',
	'Simple Backup': 'files',
	'Victor': 'files',
	'Conflict Resolution': 'developer tools',
	'Get Notebook ID': 'developer tools',
	'CodeMirror Line Numbers': 'appearance',
	'Rich Markdown': 'editing',
	'Insert Date': 'editing',
	'Note Variables': 'editing',
	'Paste Special': 'editing',
	'Table Formatter Plugin': 'editing',
	'BibTeX': 'integrations',
	'Email Note': 'integrations',
	'Export To SSG': 'integrations',
	'Pages Publisher': 'integrations',
	'Bible Quote': 'integrations',
	'Jira Issue': 'integrations',
	'Joplin Anki Sync': 'integration',
	'joplin-hackmd': 'integrations',
	'NLR': 'integrations',
	'PlantUML2': 'integrations',
	'Home Note': 'appearance',
	'Note Tabs': 'appearance',
	'Menu items, Shortcuts, Toolbar icons': 'appearance',
	'Note list and sidebar toggle buttons': 'appearance',
	'Favorites': 'appearance',
	'Notes Station Import': 'appearance',
	'Outline': 'appearance',
	'Persistent Editor Layout': 'appearance',
	'Autolinker': 'personal knowledge management',
	'Automatic Backlinks to note': 'personal knowledge management',
	'Copy Anchor Link': 'personal knowledge management',
	'Copy link to active note': 'personal knowledge management',
	'GitHub Theme': 'themes', 
	'macOS theme': 'themes',
	'White Theme': 'themes',
	'ABC Sheet Music Plugin':'viewer',
	'Admonition markdown extension': 'viewer',
	'Better Markdown Viewer': 'viewer',
	'Embed Search': 'search',
	'Make All Links': 'search',
	'Resource Search Plugin': 'search',
	'Create and go to #tags and @notebooks': 'tags',
	'Inline tags': 'tags',
	'Tag Links': 'tags',
	'Tags Generator': 'tags',
	'bytefield-svg': 'editor',
	'Code Section': 'editor',
	'Folding in Code Mirror Editor': 'editor',
	'Agenda': 'productivity',
	'Auto Alarm': 'productivity',
	'Day Review': 'productivity',
	'Kanban': 'productivity',
};
return pluginCategoriesOptions;
}

// export default pluginCategories;
