import '../../testing/test-utils';
import '../../testing/dom-test-environment';
import InteropService_Importer_OneNote from './InteropService_Importer_OneNote';
import Setting from '../../models/Setting';

describe('InteropService_Importer_OneNote.postprocessHtml', () => {
	it.each([
		{
			label: 'should gracefully handle unsupported onenote: protocol links',
			before: '<a href="onenote:///some/unsupported/uri/">Test</a>',
			after: '<a href="onenote:///some/unsupported/uri/">Test</a>',
		},
	])('$label', async ({ before, after }) => {
		// The importer needs a parent directory. Usually, this directory would contain the intermediate
		// HTML files generated by the importer or the input files. However, for this test, there are no
		// input or intermediate files, so use the empty temp directory created by the test setup logic:
		const testImportDirectory = Setting.value('tempDir');

		const importer = new InteropService_Importer_OneNote();
		await importer.init(testImportDirectory, {
			domParser: new DOMParser(),
			xmlSerializer: new XMLSerializer(),
		});

		const normalizeOutput = (output: string) => output.replace(/^<!DOCTYPE html>/, '');
		expect(
			normalizeOutput((await importer.postprocessGeneratedHtml_(before, testImportDirectory)).html),
		).toBe(after);
	});
});
