name: Bug Report
description: Report a reproducible bug or regression in Joplin.
labels: ['type: bug']

body:

  - type: dropdown
    id: os
    choices:
      - "Windows"
      - "macOS"
      - "Linux"
      - "Android"
      - "iOS"
    attributes:
      label: "Operating system"
      multiple: false
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: "Application version"
      placeholder: "x.y.z"
      description: 
    validations:
      required: true
      
  - type: textarea
    id: desktop-about-content
    attributes:
      label: "Desktop: About dialog content"
      description: "If this issue is about the **desktop app**, please copy and paste the content of the About dialog here"
  
  - type: textarea
    id: current
    attributes:
      label: Current behaviour
      description: What did Joplin do? Include screenshots and video recordings for UI problems if needed. If you are reporting a clipper bug, please include an example URL that shows the issue.
      placeholder: |
        1. This
        2. Then that
        3. Then this
        4. Etc.

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect Joplin to do?

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "If relevant, please provide a log file as described here: https://joplinapp.org/help/apps/debugging"
