import { isHashedPassword, hashPassword } from '../../utils/auth';

describe('isHashedPassword', () => {

	// cSpell:disable

	// --- VALID BCRYPT HASHES (should return true) ---

	it.each([
		['$2a$10$LMKVPiNOWDZhtw9NizNIEuNGLsjOxQAcrwQJ0lnKuiaOtyFgZEnwO', 'legacy $2a$10 hash'],
		['$2a$12$k8mM5jKSToyg0gh9VYx2r.OAFeMGPGGh/VwML3PnB/KYkVheTgFiy', '$2a$12 upgraded cost factor'],
		['$2b$12$WApznUPhDubN0oeveSXHp.Iw2aHPWMJfVCONONSiyGjmtLEApjoG6', 'modern $2b version'],
		['$2b$10$nOUIs5kJ7naTuTFkBy1veuK0kSxUFXfuaOKdOKf9xYT0KKIGSJwFa', '$2b$10 hash'],
		['$2y$08$J1Dh2F1BQ2jXeB3fFZ6Kx.VkFqG9/N2bPEqmlT4knlNI.LxZauz2y', 'PHP-compatible $2y version'],
		['$2a$04$e7xJLsMd5pReO.XDIonFSupVxldK/OGGrd7UyI1MZSakz7R6D8elO', 'low cost factor $2a$04'],
		['$2a$31$LMKVPiNOWDZhtw9NizNIEuNGLsjOxQAcrwQJ0lnKuiaOtyFgZEnwO', 'max cost factor $2a$31'],
		['$2a$08$LMKVPiNOWDZhtw9NizNIEuNGLsjOxQAcrwQJ0lnKuiaOtyFgZEnwO', 'mid cost factor $2a$08'],
	])('should detect valid bcrypt hash: %s (%s)', (hash) => {
		expect(isHashedPassword(hash)).toBe(true);
	});

	// --- REAL BCRYPT HASH GENERATION (end-to-end) ---

	it('should detect a hash generated by hashPassword()', async () => {
		const hash = await hashPassword('mySecurePassword123!');
		expect(isHashedPassword(hash)).toBe(true);
	});

	it('should detect hashes from different passwords', async () => {
		const hash1 = await hashPassword('password1');
		const hash2 = await hashPassword('anotherPassword!@#');
		expect(isHashedPassword(hash1)).toBe(true);
		expect(isHashedPassword(hash2)).toBe(true);
	});

	// --- PLAINTEXT PASSWORDS (should return false) ---

	it.each([
		'password',
		'123456',
		'simple-password-that-takes-is-long',
		'nuXUhqecx!RzK3wv6^xYaVEP%9fc$T%$E2k%9Q&TKvtDhR#2PUw3kA8KX3w2baAD8m#N9@52!DvfYn*X6hP#uAvpGF57*H9avcoePbR&4Q2XzckJnSW*EVm4G@a#YvnR',
		'P@ssw0rd!',
		'correct horse battery staple',
		'admin',
		'letmein',
	])('should reject plaintext password: %s', (password) => {
		expect(isHashedPassword(password)).toBe(false);
	});

	// --- EDGE CASES (should return false) ---

	it.each([
		['', 'empty string'],
		['$2a$10', 'truncated prefix without trailing $'],
		['$2a$10$', 'prefix with trailing $ but no hash body'],
		['$2', 'incomplete bcrypt prefix'],
		['$5$rounds=5000$saltsalt$hash', 'SHA-256 crypt format'],
		['$6$rounds=5000$saltsalt$hash', 'SHA-512 crypt format'],
		['$1$salt$hashvalue', 'MD5 crypt format'],
		['$$$$', 'just dollar signs'],
		['$2c$10$LMKVPiNOWDZhtw9NizNIEuNGLsjOxQAcrwQJ0lnKuiaOtyFgZEnwO', 'invalid bcrypt version $2c'],
		['$2a$1$invalidcostfactor', 'single digit cost factor'],
		['$2a$100$invalidcostfactor', 'three digit cost factor'],
		['mypassword$2a$10$notahash', 'hash pattern in middle of string'],
		['   ', 'whitespace-only string'],
		['\n$2a$10$LMKVPiNOWDZhtw9NizNIEuNGLsjOxQAcrwQJ0lnKuiaOtyFgZEnwO', 'newline before hash'],
	])('should reject edge case: %s (%s)', (password) => {
		expect(isHashedPassword(password)).toBe(false);
	});

	// cSpell:enable

});
