import { isHashedPassword, hashPassword } from '../../utils/auth';

describe('isHashedPassword', () => {

	// cSpell:disable

	// --- VALID BCRYPT HASHES (should return true) ---

	describe('should accept valid bcrypt hashes', () => {

		it('should detect legacy $2a$10 hashes', () => {
			expect(isHashedPassword('$2a$10$LMKVPiNOWDZhtw9NizNIEuNGLsjOxQAcrwQJ0lnKuiaOtyFgZEnwO')).toBe(true);
		});

		it('should detect $2a$12 hashes (upgraded cost factor)', () => {
			expect(isHashedPassword('$2a$12$rX9jEsODPMDiGblGlShyUeB7zNxq.MQijFcOPKLerBHDFkOwJuDYO')).toBe(true);
		});

		it('should detect $2b hashes (modern algorithm version)', () => {
			expect(isHashedPassword('$2b$12$WApznUPhDubN0oeveSXHp.Iw2aHPWMJfVCONONSiyGjmtLEApjoG6')).toBe(true);
		});

		it('should detect $2y hashes (PHP-compatible version)', () => {
			expect(isHashedPassword('$2y$08$somerandomsaltandhashedvaluehere1234567890AB')).toBe(true);
		});

		it('should detect low cost factor $2a$04 hashes', () => {
			expect(isHashedPassword('$2a$04$somerandomsaltandhashedvaluehere1234567890AB')).toBe(true);
		});

		it('should detect high cost factor $2a$31 hashes', () => {
			expect(isHashedPassword('$2a$31$somerandomsaltandhashedvaluehere1234567890AB')).toBe(true);
		});

		it('should detect $2b$10 hashes', () => {
			expect(isHashedPassword('$2b$10$nOUIs5kJ7naTuTFkBy1veuK0kSxUFXfuaOKdOKf9xYT0KKIGSJwFa')).toBe(true);
		});

		it('should detect $2a$08 hashes', () => {
			expect(isHashedPassword('$2a$08$XYZabc123def456ghi789jklmnopqrstuvwxyz012345')).toBe(true);
		});

	});

	// --- REAL BCRYPT HASH GENERATION (end-to-end verification) ---

	describe('should work with actually generated hashes', () => {

		it('should detect a hash generated by hashPassword()', async () => {
			const hash = await hashPassword('mySecurePassword123!');
			expect(isHashedPassword(hash)).toBe(true);
		});

		it('should detect hashes from different passwords', async () => {
			const hash1 = await hashPassword('password1');
			const hash2 = await hashPassword('anotherPassword!@#');
			expect(isHashedPassword(hash1)).toBe(true);
			expect(isHashedPassword(hash2)).toBe(true);
		});

	});

	// --- PLAINTEXT PASSWORDS (should return false) ---

	describe('should reject plaintext passwords', () => {

		it.each(
			[
				'password',
				'123456',
				'simple-password-that-takes-is-long',
				'nuXUhqecx!RzK3wv6^xYaVEP%9fc$T%$E2k%9Q&TKvtDhR#2PUw3kA8KX3w2baAD8m#N9@52!DvfYn*X6hP#uAvpGF57*H9avcoePbR&4Q2XzckJnSW*EVm4G@a#YvnR',
				'P@ssw0rd!',
				'correct horse battery staple',
				'admin',
				'letmein',
			],
		)('should reject plaintext password: %s', (password) => {
			expect(isHashedPassword(password)).toBe(false);
		});

	});

	// --- EDGE CASES (should return false) ---

	describe('should reject edge cases', () => {

		it('should reject empty string', () => {
			expect(isHashedPassword('')).toBe(false);
		});

		it('should reject truncated bcrypt prefix without trailing $', () => {
			expect(isHashedPassword('$2a$10')).toBe(false);
		});

		it('should reject strings that merely start with $2', () => {
			expect(isHashedPassword('$2')).toBe(false);
		});

		it('should reject non-bcrypt hash formats (SHA-256 crypt)', () => {
			expect(isHashedPassword('$5$rounds=5000$saltsalt$hash')).toBe(false);
		});

		it('should reject non-bcrypt hash formats (SHA-512 crypt)', () => {
			expect(isHashedPassword('$6$rounds=5000$saltsalt$hash')).toBe(false);
		});

		it('should reject MD5 crypt format', () => {
			expect(isHashedPassword('$1$salt$hashvalue')).toBe(false);
		});

		it('should reject just dollar signs', () => {
			expect(isHashedPassword('$$$$')).toBe(false);
		});

		it('should reject invalid bcrypt version $2c', () => {
			expect(isHashedPassword('$2c$10$LMKVPiNOWDZhtw9NizNIEuNGLsjOxQAcrwQJ0lnKuiaOtyFgZEnwO')).toBe(false);
		});

		it('should reject bcrypt-like string with single digit cost', () => {
			expect(isHashedPassword('$2a$1$invalidcostfactor')).toBe(false);
		});

		it('should reject bcrypt-like string with three digit cost', () => {
			expect(isHashedPassword('$2a$100$invalidcostfactor')).toBe(false);
		});

		it('should reject password containing $2a$10 in the middle', () => {
			expect(isHashedPassword('mypassword$2a$10$notahash')).toBe(false);
		});

		it('should reject whitespace-only strings', () => {
			expect(isHashedPassword('   ')).toBe(false);
		});

		it('should reject string with newline before hash', () => {
			expect(isHashedPassword('\n$2a$10$LMKVPiNOWDZhtw9NizNIEu')).toBe(false);
		});

	});

	// cSpell:enable

});
