nodeLinker: node-modules

# Workaround: May 29th, 2026: The default Electron installer is unreliable in CI
# with recent versions of NodeJS.
#
# To resolve this, we patch Electron to use a different library for ZIP
# extraction. This requires a dependency override because Yarn patches
# can't change the dependency tree:
# https://yarnpkg.com/features/patching#limitations
packageExtensions: {
  electron@*: {
    dependencies: {
      adm-zip: "0.5.16"
    }
  }
}