"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ItemFlow = void 0;
// AUTO-GENERATED by generate-database-type
var ItemFlow;
(function (ItemFlow) {
    ItemFlow["TopToBottom"] = "topToBottom";
    ItemFlow["LeftToRight"] = "leftToRight";
})(ItemFlow || (exports.ItemFlow = ItemFlow = {}));
//# sourceMappingURL=noteListType.js.map