on: push

name: Continuous integration

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        args:
          - '--no-default-features'
        include:
          - rust: nightly
            args: '--features backtrace'

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.args }}

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.args }}

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: ${{ matrix.args }} -- -D warnings

      - uses: EmbarkStudios/cargo-deny-action@v1