const gulp = require('gulp');
const fs = require('fs-extra');
const version = require('./package.json').version;

function compileLibPackageInfo(cb) {
	// body omitted
	console.log(`${__dirname}/packageInfo.js`);

	const file_content = `// Auto-generated by packages\\lib\\gulpfile.js
// Do not change directly
const packageInfo = {
    "version": "${version}"
};
module.exports = packageInfo;
`;
	fs.writeFileSync(`${__dirname}/packageInfo.js`, file_content);
	cb();
}

gulp.task('build', gulp.parallel(compileLibPackageInfo));
