jest.mock('react-native', () => {
	return {
		__esModule: true,
		Dimensions: {
			get: jest.fn()
				.mockReturnValueOnce({ width: 400 }) 	// Screen width returned for 1st call of getResponsiveValue()
				.mockReturnValueOnce({ width: 400 }) 	//       ...
				.mockReturnValueOnce({ width: 400 }) 	//       ...
				.mockReturnValueOnce({ width: 480 }) 	//       ...
				.mockReturnValueOnce({ width: 481 }) 	//       ...
				.mockReturnValueOnce({ width: 600 }) 	//       ...
				.mockReturnValueOnce({ width: 768 }) 	//       ...
				.mockReturnValueOnce({ width: 769 }) 	//       ...
				.mockReturnValueOnce({ width: 900 }) 	//       ...
				.mockReturnValueOnce({ width: 1024 }) 	//       ...
				.mockReturnValueOnce({ width: 1025 }) 	//       ...
				.mockReturnValueOnce({ width: 1200 }) 	//       ...
				.mockReturnValueOnce({ width: 1201 }) 	//       ...
				.mockReturnValueOnce({ width: 1300 }),	// Screen width returned for 12th call of getResponsiveValue()
		},
	};
});

