"use strict";
/* eslint-disable multiline-comment-style */
Object.defineProperty(exports, "__esModule", { value: true });
const Joplin_1 = require("./Joplin");
/**
 * @ignore
 */
// const builtinModules = require('builtin-modules');
/**
 * @ignore
 */
class Global {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Old code before rule was applied
    constructor(implementation, plugin, store) {
        this.joplin_ = new Joplin_1.default(implementation, plugin, store);
    }
    get joplin() {
        return this.joplin_;
    }
    // To get webpack to work with Node module we need to set the parameter `target: "node"`, however
    // when setting this, the code generated by webpack will try to access the `process` global variable,
    // which won't be defined in the sandbox. So here we simply forward the variable, which makes it all work.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Old code before rule was applied
    get process() {
        return process;
    }
}
exports.default = Global;
