"use strict";
/* eslint-disable multiline-comment-style */
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultListColumns = exports.defaultWidth = exports.columnNames = exports.ItemFlow = void 0;
// AUTO-GENERATED by generate-database-type
var ItemFlow;
(function (ItemFlow) {
    ItemFlow["TopToBottom"] = "topToBottom";
    ItemFlow["LeftToRight"] = "leftToRight";
})(ItemFlow || (exports.ItemFlow = ItemFlow = {}));
exports.columnNames = [
    'note.folder.title',
    'note.is_todo',
    'note.latitude',
    'note.longitude',
    'note.source_url',
    'note.tags',
    'note.title',
    'note.todo_completed',
    'note.todo_due',
    'note.user_created_time',
    'note.user_updated_time',
];
exports.defaultWidth = 100;
const defaultListColumns = () => {
    const columns = [
        {
            name: 'note.is_todo',
            width: 30,
        },
        {
            name: 'note.user_updated_time',
            width: exports.defaultWidth,
        },
        {
            name: 'note.title',
            width: 0,
        },
    ];
    return columns;
};
exports.defaultListColumns = defaultListColumns;
