var locales = {};
var stats = {};
locales['en_GB'] = require('./en_GB.json');
locales['ar'] = require('./ar.json');
locales['bg_BG'] = require('./bg_BG.json');
locales['bs_BA'] = require('./bs_BA.json');
locales['ca'] = require('./ca.json');
locales['cs_CZ'] = require('./cs_CZ.json');
locales['da_DK'] = require('./da_DK.json');
locales['de_DE'] = require('./de_DE.json');
locales['el_GR'] = require('./el_GR.json');
locales['en_US'] = require('./en_US.json');
locales['eo'] = require('./eo.json');
locales['es_ES'] = require('./es_ES.json');
locales['et_EE'] = require('./et_EE.json');
locales['eu'] = require('./eu.json');
locales['fa'] = require('./fa.json');
locales['fi_FI'] = require('./fi_FI.json');
locales['fr_FR'] = require('./fr_FR.json');
locales['gl_ES'] = require('./gl_ES.json');
locales['hr_HR'] = require('./hr_HR.json');
locales['hu_HU'] = require('./hu_HU.json');
locales['id_ID'] = require('./id_ID.json');
locales['it_IT'] = require('./it_IT.json');
locales['ja_JP'] = require('./ja_JP.json');
locales['ko'] = require('./ko.json');
locales['nb_NO'] = require('./nb_NO.json');
locales['nl_BE'] = require('./nl_BE.json');
locales['nl_NL'] = require('./nl_NL.json');
locales['pl_PL'] = require('./pl_PL.json');
locales['pt_BR'] = require('./pt_BR.json');
locales['pt_PT'] = require('./pt_PT.json');
locales['ro_MD'] = require('./ro_MD.json');
locales['ro_RO'] = require('./ro_RO.json');
locales['ru_RU'] = require('./ru_RU.json');
locales['sk_SK'] = require('./sk_SK.json');
locales['sl_SI'] = require('./sl_SI.json');
locales['sr_RS'] = require('./sr_RS.json');
locales['sv'] = require('./sv.json');
locales['th_TH'] = require('./th_TH.json');
locales['tr_TR'] = require('./tr_TR.json');
locales['uk_UA'] = require('./uk_UA.json');
locales['vi'] = require('./vi.json');
locales['zh_CN'] = require('./zh_CN.json');
locales['zh_TW'] = require('./zh_TW.json');
stats['ar'] = {
	percentDone: 57,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['eu'] = {
	percentDone: 15,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['nb_NO'] = {
	percentDone: 57,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['bs_BA'] = {
	percentDone: 37,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['bg_BG'] = {
	percentDone: 29,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['ca'] = {
	percentDone: 98,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['hr_HR'] = {
	percentDone: 98,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['cs_CZ'] = {
	percentDone: 64,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['da_DK'] = {
	percentDone: 98,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['de_DE'] = {
	percentDone: 98,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['et_EE'] = {
	percentDone: 28,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['en_GB'] = {
	percentDone: 100,
	
};
stats['en_US'] = {
	percentDone: 100,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['es_ES'] = {
	percentDone: 98,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['eo'] = {
	percentDone: 16,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['fi_FI'] = {
	percentDone: 87,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['fr_FR'] = {
	percentDone: 100,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n > 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['gl_ES'] = {
	percentDone: 89,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['id_ID'] = {
	percentDone: 98,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=1; plural=0;
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['it_IT'] = {
	percentDone: 78,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['hu_HU'] = {
	percentDone: 98,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['nl_BE'] = {
	percentDone: 84,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['nl_NL'] = {
	percentDone: 89,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['fa'] = {
	percentDone: 78,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n==0 || n==1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['pl_PL'] = {
	percentDone: 92,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['pt_BR'] = {
	percentDone: 89,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n > 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['pt_PT'] = {
	percentDone: 78,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['ro_MD'] = {
	percentDone: 97,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=3; plural=(n==1 ? 0 : n==0 || (n!=1 && n%100>=1 && n%100<=19) ? 1 : 2);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['ro_RO'] = {
	percentDone: 97,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=3; plural=(n==1 ? 0 : n==0 || (n!=1 && n%100>=1 && n%100<=19) ? 1 : 2);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['sl_SI'] = {
	percentDone: 52,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=4; plural=(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['sk_SK'] = {
	percentDone: 98,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=3; plural=(n==1 ? 0 : n>=2 && n<=4 ? 1 : 2);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['sv'] = {
	percentDone: 98,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['th_TH'] = {
	percentDone: 23,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=1; plural=0;
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['vi'] = {
	percentDone: 50,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=1; plural=0;
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['tr_TR'] = {
	percentDone: 97,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['uk_UA'] = {
	percentDone: 84,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['el_GR'] = {
	percentDone: 86,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=2; plural=(n != 1);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['ru_RU'] = {
	percentDone: 96,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['sr_RS'] = {
	percentDone: 42,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['zh_CN'] = {
	percentDone: 96,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=1; plural=0;
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['zh_TW'] = {
	percentDone: 78,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=1; plural=0;
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['ja_JP'] = {
	percentDone: 71,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=1; plural=0;
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
stats['ko'] = {
	percentDone: 72,
	pluralForms: function(n) {
		// AUTO-GENERATED by build-translations.ts
		var plural;
		var nplurals;
		nplurals=1; plural=0;
		return (plural === true ? 1 : plural ? plural : 0);
	},
};
module.exports = { locales: locales, stats: stats };