// Here we replicate what's being done in highlight.js/index.js by default,
// except that we exclude a number of very large, but not very useful languages
// (those commented out).
//
// https://github.com/highlightjs/highlight.js/issues/1257#issuecomment-254502834


// hljs.registerLanguage('1c', _1c_317);
import _1c_317 from 'highlight.js/lib/languages/1c';
import abnf_318 from 'highlight.js/lib/languages/abnf';
import accesslog_319 from 'highlight.js/lib/languages/accesslog';
import actionscript_320 from 'highlight.js/lib/languages/actionscript';
import ada_321 from 'highlight.js/lib/languages/ada';
import angelscript_322 from 'highlight.js/lib/languages/angelscript';
import apache_323 from 'highlight.js/lib/languages/apache';
import applescript_324 from 'highlight.js/lib/languages/applescript';
import arcade_325 from 'highlight.js/lib/languages/arcade';
import arduino_326 from 'highlight.js/lib/languages/arduino';
import armasm_327 from 'highlight.js/lib/languages/armasm';
import xml_328 from 'highlight.js/lib/languages/xml';
import asciidoc_329 from 'highlight.js/lib/languages/asciidoc';
import aspectj_330 from 'highlight.js/lib/languages/aspectj';
import autohotkey_331 from 'highlight.js/lib/languages/autohotkey';
import autoit_332 from 'highlight.js/lib/languages/autoit';
import avrasm_333 from 'highlight.js/lib/languages/avrasm';
import awk_334 from 'highlight.js/lib/languages/awk';
import axapta_335 from 'highlight.js/lib/languages/axapta';
import bash_336 from 'highlight.js/lib/languages/bash';
import basic_337 from 'highlight.js/lib/languages/basic';
import bnf_338 from 'highlight.js/lib/languages/bnf';
import brainfuck_339 from 'highlight.js/lib/languages/brainfuck';
import c_340 from 'highlight.js/lib/languages/c';
import cal_341 from 'highlight.js/lib/languages/cal';
import capnproto_342 from 'highlight.js/lib/languages/capnproto';
import ceylon_343 from 'highlight.js/lib/languages/ceylon';
import clean_344 from 'highlight.js/lib/languages/clean';
import clojure_345 from 'highlight.js/lib/languages/clojure';
import clojure_repl_346 from 'highlight.js/lib/languages/clojure-repl';
import cmake_347 from 'highlight.js/lib/languages/cmake';
import coffeescript_348 from 'highlight.js/lib/languages/coffeescript';
import coq_349 from 'highlight.js/lib/languages/coq';
import cos_350 from 'highlight.js/lib/languages/cos';
import cpp_351 from 'highlight.js/lib/languages/cpp';
import crmsh_352 from 'highlight.js/lib/languages/crmsh';
import crystal_353 from 'highlight.js/lib/languages/crystal';
import csharp_354 from 'highlight.js/lib/languages/csharp';
import csp_355 from 'highlight.js/lib/languages/csp';
import css_356 from 'highlight.js/lib/languages/css';
import d_357 from 'highlight.js/lib/languages/d';
import markdown_358 from 'highlight.js/lib/languages/markdown';
import dart_359 from 'highlight.js/lib/languages/dart';
import delphi_360 from 'highlight.js/lib/languages/delphi';
import diff_361 from 'highlight.js/lib/languages/diff';
import django_362 from 'highlight.js/lib/languages/django';
import dns_363 from 'highlight.js/lib/languages/dns';
import dockerfile_364 from 'highlight.js/lib/languages/dockerfile';
import dos_365 from 'highlight.js/lib/languages/dos';
import dsconfig_366 from 'highlight.js/lib/languages/dsconfig';
import dts_367 from 'highlight.js/lib/languages/dts';
import dust_368 from 'highlight.js/lib/languages/dust';
import ebnf_369 from 'highlight.js/lib/languages/ebnf';
import elixir_370 from 'highlight.js/lib/languages/elixir';
import elm_371 from 'highlight.js/lib/languages/elm';
import ruby_372 from 'highlight.js/lib/languages/ruby';
import erb_373 from 'highlight.js/lib/languages/erb';
import erlang_repl_374 from 'highlight.js/lib/languages/erlang-repl';
import erlang_375 from 'highlight.js/lib/languages/erlang';
import excel_376 from 'highlight.js/lib/languages/excel';
import fix_377 from 'highlight.js/lib/languages/fix';
import flix_378 from 'highlight.js/lib/languages/flix';
import fortran_379 from 'highlight.js/lib/languages/fortran';
import fsharp_380 from 'highlight.js/lib/languages/fsharp';
import gams_381 from 'highlight.js/lib/languages/gams';
import gauss_382 from 'highlight.js/lib/languages/gauss';
import gcode_383 from 'highlight.js/lib/languages/gcode';
import gherkin_384 from 'highlight.js/lib/languages/gherkin';
import glsl_385 from 'highlight.js/lib/languages/glsl';
import gml_386 from 'highlight.js/lib/languages/gml';
import go_387 from 'highlight.js/lib/languages/go';
import golo_388 from 'highlight.js/lib/languages/golo';
import gradle_389 from 'highlight.js/lib/languages/gradle';
import groovy_390 from 'highlight.js/lib/languages/groovy';
import haml_391 from 'highlight.js/lib/languages/haml';
import handlebars_392 from 'highlight.js/lib/languages/handlebars';
import haskell_393 from 'highlight.js/lib/languages/haskell';
import haxe_394 from 'highlight.js/lib/languages/haxe';
import hsp_395 from 'highlight.js/lib/languages/hsp';
import http_396 from 'highlight.js/lib/languages/http';
import hy_397 from 'highlight.js/lib/languages/hy';
import inform7_398 from 'highlight.js/lib/languages/inform7';
import ini_399 from 'highlight.js/lib/languages/ini';
import irpf90_400 from 'highlight.js/lib/languages/irpf90';
import isbl_401 from 'highlight.js/lib/languages/isbl';
import java_402 from 'highlight.js/lib/languages/java';
import javascript_403 from 'highlight.js/lib/languages/javascript';
import jboss_cli_404 from 'highlight.js/lib/languages/jboss-cli';
import json_405 from 'highlight.js/lib/languages/json';
import julia_406 from 'highlight.js/lib/languages/julia';
import julia_repl_407 from 'highlight.js/lib/languages/julia-repl';
import kotlin_408 from 'highlight.js/lib/languages/kotlin';
import lasso_409 from 'highlight.js/lib/languages/lasso';
import latex_410 from 'highlight.js/lib/languages/latex';
import ldif_411 from 'highlight.js/lib/languages/ldif';
import leaf_412 from 'highlight.js/lib/languages/leaf';
import less_413 from 'highlight.js/lib/languages/less';
import lisp_414 from 'highlight.js/lib/languages/lisp';
import livecodeserver_415 from 'highlight.js/lib/languages/livecodeserver';
import livescript_416 from 'highlight.js/lib/languages/livescript';
import llvm_417 from 'highlight.js/lib/languages/llvm';
import lsl_418 from 'highlight.js/lib/languages/lsl';
import lua_419 from 'highlight.js/lib/languages/lua';
import makefile_420 from 'highlight.js/lib/languages/makefile';
import mathematica_421 from 'highlight.js/lib/languages/mathematica';
import matlab_422 from 'highlight.js/lib/languages/matlab';
import maxima_423 from 'highlight.js/lib/languages/maxima';
import mel_424 from 'highlight.js/lib/languages/mel';
import mercury_425 from 'highlight.js/lib/languages/mercury';
import mipsasm_426 from 'highlight.js/lib/languages/mipsasm';
import mizar_427 from 'highlight.js/lib/languages/mizar';
import perl_428 from 'highlight.js/lib/languages/perl';
import mojolicious_429 from 'highlight.js/lib/languages/mojolicious';
import monkey_430 from 'highlight.js/lib/languages/monkey';
import moonscript_431 from 'highlight.js/lib/languages/moonscript';
import n1ql_432 from 'highlight.js/lib/languages/n1ql';
import nestedtext_433 from 'highlight.js/lib/languages/nestedtext';
import nginx_434 from 'highlight.js/lib/languages/nginx';
import nim_435 from 'highlight.js/lib/languages/nim';
import nix_436 from 'highlight.js/lib/languages/nix';
import node_repl_437 from 'highlight.js/lib/languages/node-repl';
import nsis_438 from 'highlight.js/lib/languages/nsis';
import objectivec_439 from 'highlight.js/lib/languages/objectivec';
import ocaml_440 from 'highlight.js/lib/languages/ocaml';
import openscad_441 from 'highlight.js/lib/languages/openscad';
import oxygene_442 from 'highlight.js/lib/languages/oxygene';
import parser3_443 from 'highlight.js/lib/languages/parser3';
import pf_444 from 'highlight.js/lib/languages/pf';
import pgsql_445 from 'highlight.js/lib/languages/pgsql';
import php_446 from 'highlight.js/lib/languages/php';
import php_template_447 from 'highlight.js/lib/languages/php-template';
import plaintext_448 from 'highlight.js/lib/languages/plaintext';
import pony_449 from 'highlight.js/lib/languages/pony';
import powershell_450 from 'highlight.js/lib/languages/powershell';
import processing_451 from 'highlight.js/lib/languages/processing';
import profile_452 from 'highlight.js/lib/languages/profile';
import prolog_453 from 'highlight.js/lib/languages/prolog';
import properties_454 from 'highlight.js/lib/languages/properties';
import protobuf_455 from 'highlight.js/lib/languages/protobuf';
import puppet_456 from 'highlight.js/lib/languages/puppet';
import purebasic_457 from 'highlight.js/lib/languages/purebasic';
import python_458 from 'highlight.js/lib/languages/python';
import python_repl_459 from 'highlight.js/lib/languages/python-repl';
import q_460 from 'highlight.js/lib/languages/q';
import qml_461 from 'highlight.js/lib/languages/qml';
import r_462 from 'highlight.js/lib/languages/r';
import reasonml_463 from 'highlight.js/lib/languages/reasonml';
import rib_464 from 'highlight.js/lib/languages/rib';
import roboconf_465 from 'highlight.js/lib/languages/roboconf';
import routeros_466 from 'highlight.js/lib/languages/routeros';
import rsl_467 from 'highlight.js/lib/languages/rsl';
import ruleslanguage_468 from 'highlight.js/lib/languages/ruleslanguage';
import rust_469 from 'highlight.js/lib/languages/rust';
import sas_470 from 'highlight.js/lib/languages/sas';
import scala_471 from 'highlight.js/lib/languages/scala';
import scheme_472 from 'highlight.js/lib/languages/scheme';
import scilab_473 from 'highlight.js/lib/languages/scilab';
import scss_474 from 'highlight.js/lib/languages/scss';
import shell_475 from 'highlight.js/lib/languages/shell';
import smali_476 from 'highlight.js/lib/languages/smali';
import smalltalk_477 from 'highlight.js/lib/languages/smalltalk';
import sml_478 from 'highlight.js/lib/languages/sml';
import sqf_479 from 'highlight.js/lib/languages/sqf';
import sql_480 from 'highlight.js/lib/languages/sql';
import stan_481 from 'highlight.js/lib/languages/stan';
import stata_482 from 'highlight.js/lib/languages/stata';
import step21_483 from 'highlight.js/lib/languages/step21';
import stylus_484 from 'highlight.js/lib/languages/stylus';
import subunit_485 from 'highlight.js/lib/languages/subunit';
import swift_486 from 'highlight.js/lib/languages/swift';
import taggerscript_487 from 'highlight.js/lib/languages/taggerscript';
import yaml_488 from 'highlight.js/lib/languages/yaml';
import tap_489 from 'highlight.js/lib/languages/tap';
import tcl_490 from 'highlight.js/lib/languages/tcl';
import thrift_491 from 'highlight.js/lib/languages/thrift';
import tp_492 from 'highlight.js/lib/languages/tp';
import twig_493 from 'highlight.js/lib/languages/twig';
import typescript_494 from 'highlight.js/lib/languages/typescript';
import vala_495 from 'highlight.js/lib/languages/vala';
import vbnet_496 from 'highlight.js/lib/languages/vbnet';
import vbscript_497 from 'highlight.js/lib/languages/vbscript';
import vbscript_html_498 from 'highlight.js/lib/languages/vbscript-html';
import verilog_499 from 'highlight.js/lib/languages/verilog';
import vhdl_500 from 'highlight.js/lib/languages/vhdl';
import vim_501 from 'highlight.js/lib/languages/vim';
import wasm_502 from 'highlight.js/lib/languages/wasm';
import wren_503 from 'highlight.js/lib/languages/wren';
import x86asm_504 from 'highlight.js/lib/languages/x86asm';
import xl_505 from 'highlight.js/lib/languages/xl';
import xquery_506 from 'highlight.js/lib/languages/xquery';
import zephir_507 from 'highlight.js/lib/languages/zephir';
import hljs from 'highlight.js/lib/core';
hljs.registerLanguage('abnf', abnf_318);
hljs.registerLanguage('accesslog', accesslog_319);
hljs.registerLanguage('actionscript', actionscript_320);
hljs.registerLanguage('ada', ada_321);
hljs.registerLanguage('angelscript', angelscript_322);
hljs.registerLanguage('apache', apache_323);
hljs.registerLanguage('applescript', applescript_324);
hljs.registerLanguage('arcade', arcade_325);
hljs.registerLanguage('arduino', arduino_326);
hljs.registerLanguage('armasm', armasm_327);
hljs.registerLanguage('xml', xml_328);
hljs.registerLanguage('asciidoc', asciidoc_329);
hljs.registerLanguage('aspectj', aspectj_330);
hljs.registerLanguage('autohotkey', autohotkey_331);
hljs.registerLanguage('autoit', autoit_332);
hljs.registerLanguage('avrasm', avrasm_333);
hljs.registerLanguage('awk', awk_334);
hljs.registerLanguage('axapta', axapta_335);
hljs.registerLanguage('bash', bash_336);
hljs.registerLanguage('basic', basic_337);
hljs.registerLanguage('bnf', bnf_338);
hljs.registerLanguage('brainfuck', brainfuck_339);
hljs.registerLanguage('c', c_340);
hljs.registerLanguage('cal', cal_341);
hljs.registerLanguage('capnproto', capnproto_342);
hljs.registerLanguage('ceylon', ceylon_343);
hljs.registerLanguage('clean', clean_344);
hljs.registerLanguage('clojure', clojure_345);
hljs.registerLanguage('clojure-repl', clojure_repl_346);
hljs.registerLanguage('cmake', cmake_347);
hljs.registerLanguage('coffeescript', coffeescript_348);
hljs.registerLanguage('coq', coq_349);
hljs.registerLanguage('cos', cos_350);
hljs.registerLanguage('cpp', cpp_351);
hljs.registerLanguage('crmsh', crmsh_352);
hljs.registerLanguage('crystal', crystal_353);
hljs.registerLanguage('csharp', csharp_354);
hljs.registerLanguage('csp', csp_355);
hljs.registerLanguage('css', css_356);
hljs.registerLanguage('d', d_357);
hljs.registerLanguage('markdown', markdown_358);
hljs.registerLanguage('dart', dart_359);
hljs.registerLanguage('delphi', delphi_360);
hljs.registerLanguage('diff', diff_361);
hljs.registerLanguage('django', django_362);
hljs.registerLanguage('dns', dns_363);
hljs.registerLanguage('dockerfile', dockerfile_364);
hljs.registerLanguage('dos', dos_365);
hljs.registerLanguage('dsconfig', dsconfig_366);
hljs.registerLanguage('dts', dts_367);
hljs.registerLanguage('dust', dust_368);
hljs.registerLanguage('ebnf', ebnf_369);
hljs.registerLanguage('elixir', elixir_370);
hljs.registerLanguage('elm', elm_371);
hljs.registerLanguage('ruby', ruby_372);
hljs.registerLanguage('erb', erb_373);
hljs.registerLanguage('erlang-repl', erlang_repl_374);
hljs.registerLanguage('erlang', erlang_375);
hljs.registerLanguage('excel', excel_376);
hljs.registerLanguage('fix', fix_377);
hljs.registerLanguage('flix', flix_378);
hljs.registerLanguage('fortran', fortran_379);
hljs.registerLanguage('fsharp', fsharp_380);
hljs.registerLanguage('gams', gams_381);
hljs.registerLanguage('gauss', gauss_382);
hljs.registerLanguage('gcode', gcode_383);
hljs.registerLanguage('gherkin', gherkin_384);
hljs.registerLanguage('glsl', glsl_385);
// hljs.registerLanguage('gml', gml_386);
hljs.registerLanguage('go', go_387);
hljs.registerLanguage('golo', golo_388);
hljs.registerLanguage('gradle', gradle_389);
hljs.registerLanguage('groovy', groovy_390);
hljs.registerLanguage('haml', haml_391);
hljs.registerLanguage('handlebars', handlebars_392);
hljs.registerLanguage('haskell', haskell_393);
hljs.registerLanguage('haxe', haxe_394);
hljs.registerLanguage('hsp', hsp_395);
hljs.registerLanguage('http', http_396);
hljs.registerLanguage('hy', hy_397);
hljs.registerLanguage('inform7', inform7_398);
hljs.registerLanguage('ini', ini_399);
hljs.registerLanguage('irpf90', irpf90_400);
// hljs.registerLanguage('isbl', isbl_401);
hljs.registerLanguage('java', java_402);
hljs.registerLanguage('javascript', javascript_403);
hljs.registerLanguage('jboss-cli', jboss_cli_404);
hljs.registerLanguage('json', json_405);
hljs.registerLanguage('julia', julia_406);
hljs.registerLanguage('julia-repl', julia_repl_407);
hljs.registerLanguage('kotlin', kotlin_408);
hljs.registerLanguage('lasso', lasso_409);
hljs.registerLanguage('latex', latex_410);
hljs.registerLanguage('ldif', ldif_411);
hljs.registerLanguage('leaf', leaf_412);
// hljs.registerLanguage('less', less_413);
hljs.registerLanguage('lisp', lisp_414);
hljs.registerLanguage('livecodeserver', livecodeserver_415);
hljs.registerLanguage('livescript', livescript_416);
hljs.registerLanguage('llvm', llvm_417);
// hljs.registerLanguage('lsl', lsl_418);
hljs.registerLanguage('lua', lua_419);
hljs.registerLanguage('makefile', makefile_420);
// hljs.registerLanguage('mathematica', mathematica_421);
hljs.registerLanguage('matlab', matlab_422);
// hljs.registerLanguage('maxima', maxima_423);
hljs.registerLanguage('mel', mel_424);
hljs.registerLanguage('mercury', mercury_425);
hljs.registerLanguage('mipsasm', mipsasm_426);
hljs.registerLanguage('mizar', mizar_427);
hljs.registerLanguage('perl', perl_428);
hljs.registerLanguage('mojolicious', mojolicious_429);
hljs.registerLanguage('monkey', monkey_430);
hljs.registerLanguage('moonscript', moonscript_431);
hljs.registerLanguage('n1ql', n1ql_432);
hljs.registerLanguage('nestedtext', nestedtext_433);
hljs.registerLanguage('nginx', nginx_434);
hljs.registerLanguage('nim', nim_435);
hljs.registerLanguage('nix', nix_436);
hljs.registerLanguage('node-repl', node_repl_437);
hljs.registerLanguage('nsis', nsis_438);
hljs.registerLanguage('objectivec', objectivec_439);
hljs.registerLanguage('ocaml', ocaml_440);
hljs.registerLanguage('openscad', openscad_441);
hljs.registerLanguage('oxygene', oxygene_442);
hljs.registerLanguage('parser3', parser3_443);
hljs.registerLanguage('pf', pf_444);
// hljs.registerLanguage('pgsql', pgsql_445);
hljs.registerLanguage('php', php_446);
hljs.registerLanguage('php-template', php_template_447);
hljs.registerLanguage('plaintext', plaintext_448);
hljs.registerLanguage('pony', pony_449);
hljs.registerLanguage('powershell', powershell_450);
hljs.registerLanguage('processing', processing_451);
hljs.registerLanguage('profile', profile_452);
hljs.registerLanguage('prolog', prolog_453);
hljs.registerLanguage('properties', properties_454);
hljs.registerLanguage('protobuf', protobuf_455);
hljs.registerLanguage('puppet', puppet_456);
hljs.registerLanguage('purebasic', purebasic_457);
hljs.registerLanguage('python', python_458);
hljs.registerLanguage('python-repl', python_repl_459);
hljs.registerLanguage('q', q_460);
hljs.registerLanguage('qml', qml_461);
hljs.registerLanguage('r', r_462);
hljs.registerLanguage('reasonml', reasonml_463);
hljs.registerLanguage('rib', rib_464);
hljs.registerLanguage('roboconf', roboconf_465);
hljs.registerLanguage('routeros', routeros_466);
hljs.registerLanguage('rsl', rsl_467);
hljs.registerLanguage('ruleslanguage', ruleslanguage_468);
hljs.registerLanguage('rust', rust_469);
hljs.registerLanguage('sas', sas_470);
hljs.registerLanguage('scala', scala_471);
hljs.registerLanguage('scheme', scheme_472);
hljs.registerLanguage('scilab', scilab_473);
hljs.registerLanguage('scss', scss_474);
hljs.registerLanguage('shell', shell_475);
hljs.registerLanguage('smali', smali_476);
hljs.registerLanguage('smalltalk', smalltalk_477);
hljs.registerLanguage('sml', sml_478);
// hljs.registerLanguage('sqf', sqf_479);
hljs.registerLanguage('sql', sql_480);
hljs.registerLanguage('stan', stan_481);
// hljs.registerLanguage('stata', stata_482);
hljs.registerLanguage('step21', step21_483);
hljs.registerLanguage('stylus', stylus_484);
hljs.registerLanguage('subunit', subunit_485);
hljs.registerLanguage('swift', swift_486);
hljs.registerLanguage('taggerscript', taggerscript_487);
hljs.registerLanguage('yaml', yaml_488);
hljs.registerLanguage('tap', tap_489);
hljs.registerLanguage('tcl', tcl_490);
hljs.registerLanguage('thrift', thrift_491);
hljs.registerLanguage('tp', tp_492);
hljs.registerLanguage('twig', twig_493);
hljs.registerLanguage('typescript', typescript_494);
hljs.registerLanguage('vala', vala_495);
hljs.registerLanguage('vbnet', vbnet_496);
hljs.registerLanguage('vbscript', vbscript_497);
hljs.registerLanguage('vbscript-html', vbscript_html_498);
hljs.registerLanguage('verilog', verilog_499);
hljs.registerLanguage('vhdl', vhdl_500);
hljs.registerLanguage('vim', vim_501);
hljs.registerLanguage('wasm', wasm_502);
hljs.registerLanguage('wren', wren_503);
hljs.registerLanguage('x86asm', x86asm_504);
hljs.registerLanguage('xl', xl_505);
hljs.registerLanguage('xquery', xquery_506);
hljs.registerLanguage('zephir', zephir_507);

export default hljs;
