import { readFile } from 'fs/promises';
import { isAutoGeneratedFile } from './checkGeneratedFiles';
import { join } from 'path';

describe('checkGeneratedFiles', () => {
	it('should detect an older auto-generated .js file processed by eslint', () => {
		const generatedFile = `
'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.default = function() {};
// # sourceMappingURL=test.js.map
`.trimStart();
		expect(isAutoGeneratedFile(generatedFile)).toBe(true);
	});

	it('should detect a newer auto-generated .js file', async () => {
		const fileContent = await readFile(join(__dirname, 'checkGeneratedFiles.test.js'), 'utf-8');
		expect(isAutoGeneratedFile(fileContent)).toBe(true);
	});
});
